### ISSUE TITLE
CORS issue for authenticated api

### ISSUE THREAD

**Issue by rahulvemula** [rahulvemula/SE-leasingPortal#142]
**Describe the bug**
CORS issue for get user api

**To Reproduce**
1. Login with a user
2. Use the token received in the token header for get user call
3. This is giving CORS error in browser

**Expected behavior**
No CORS issue

**Screenshots**
![image](https://user-images.githubusercontent.com/8132049/160927384-103974c8-4795-4bee-9d7a-8a8ea0fc011d.png)

**Additional context**
token is not added in the allowed headers in the GO lang code

**Comment by mitulmandaliya** [comment]
@rahulvemula I pushed a change. Can you check if it's working?

**Comment by rahulvemula** [comment]
Its working now. Will close the issue
