### ISSUE TITLE
Create tables for DB

### ISSUE THREAD

**Issue by lbarad** [rahulvemula/SE-leasingPortal#6]
Epic link: #5

**Comment by rahulvemula** [comment]
Tables needed for the initial sprint sorted from high priority to low priority:

TABLE 1:
Society table:
societyId - primary
societyName
societyAddress
societyAmenities - arr

TABLE 2:
Listing table:
lisitingId
listingType - enum (0 house 1 bedroom)
houseType - enum (1/2/3/4 bhk)
Rent 
societyId - foreign key to soc table
isLeased - boolean

TABLE 3:
User table:
userID
userName
firstName
lastName
phoneNumber

TABLE 4:
Lease table:
leaseId  - primary
lisitingId - foreign
userID - foreign
leaseStartDate
leaseEndDate


This should suffice for the initial API development for listSocieties, listListings. Additional columns can be added to these tables according to requirement when the new stories are picked up.

**Comment by mitulmandaliya** [comment]
1) What's listingType and houseType in Listing table?
2) We should also include email address in User table.
3) How are we going to use Lease table?
4) Should we change table name Society to Property/Apartment?

**Comment by vamsibvv** [comment]
@rahulvemula @lbarad @mitulmandaliya 
We will prioritize tables for this sprint alone and write the apis only for those tables.
Right now we can have a user registration table and simple lease info table in our db.
