### ISSUE TITLE
CORS Exception

### ISSUE THREAD

**Issue by rahulvemula** [rahulvemula/SE-leasingPortal#94]
**Describe the bug**
The APIs created couldn't be accessed from the frontend as there is no cors policy setup.

**To Reproduce**
1. Go to leasing portal
2. Click on register
3. Provide details 
4. open network tab and click submit. You'll find that the network call has failed due to CORS issue

**Expected behavior**
Registration should happen

**Comment by mitulmandaliya** [comment]
@vamsibvv @rahulvemula working on it

**Comment by mitulmandaliya** [comment]
@rahulvemula Can you test now?

**Comment by lbarad** [comment]
Addressed in sprint 2
